# Generated by Django 6.0 on 2026-01-12 05:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('content', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('url', models.TextField(unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('last_crawled', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='api_webpage_search__7dfbbd_gin')],
            },
        ),
    ]
