# Generated by Django 6.0 on 2026-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webpage',
            index=models.Index(fields=['content_hash'], name='contetn-hash-index'),
        ),
    ]
